# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /myapp

# Install PostgreSQL development libraries
RUN apt-get update --fix-missing && apt-get install -y \
    libpq-dev \
    gcc \
    && apt-get clean
    
COPY ./requirements_streamlit.txt /myapp/requirements_streamlit.txt


# Upgrade pip and setuptools
RUN pip install --upgrade pip setuptools

# Install dependencies

RUN pip install --no-cache-dir -r requirements_streamlit.txt

# Copy the entire project directory into the container
#  TODO Donot copy entire project..only frontend part
# Copy the contents of the visualization folder to /myapp/visualization in the container


# Copy only the visualization directory into the container
COPY ./visualization /myapp/visualization
COPY .env.streamlit /myapp/.env.streamlit

# Expose port 8501 for Streamlit
EXPOSE 8501

# Run Streamlit app by default
CMD ["streamlit", "run", "/myapp/visualization/dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
