# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    timeout-minutes: 120 # Increase the timeout to 2 hours
    runs-on: self-hosted
    environment: testing

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Create .env file
        run: |
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
          echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
          echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
          echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          echo "SERVER_ENDPOINT=${{ secrets.SERVER_ENDPOINT }}" >> .env.streamlit
          echo "API_ENDPOINT=${{ secrets.API_ENDPOINT }}" >> .env
          echo "BEARER_TOKEN=${{ secrets.BEARER_TOKEN }}" >> .env
          echo "SUPABASE_API_KEY=${{ secrets.SUPABASE_API_KEY }}" >> .env
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "BUCKET_NAME=${{ secrets.BUCKET_NAME }}" >> .env
          cat .env.streamlit

      # Added step to build and start all docker container
      - name: Build Docker container
        run: docker-compose up -d --build

      - name: Get Runner IP
        run: |
          echo "Private IP: $(hostname -I | awk '{print $1}')"
          echo "Public IP: $(curl -s ifconfig.me)"
